Repository CAT-Technologies/GrocerEase, pull requests merged in 2022-03, with the labels that each got.

#43 flowchart for main program added (issue #35)
  utils/main program flowchart/code.txt
  utils/main program flowchart/flowchart.png
Labels: documentation, priority: high

#55 Create design_logs.md
  Hardware/Design/logs.md
Labels: enhancement, design, priority: high

#53 adding code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation
